name:                PFAD
version:             0.1.0.0
github:              "isao-takejib/PFAD"
license:             BSD3
author:              "Isao TAKEJI"
maintainer:          "isao.takeji.bigmoon@gmail.com"
copyright:           "2020 Isao TAKEJI"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isao-takejib/PFAD#readme>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  minfree:
    main:                app/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
  fastMinfree:
    main: app/FastMinfreeApp.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
tests:
  PFAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFAD
    - hspec
    - QuickCheck
